apiVersion: v1
kind: ServiceAccount
metadata:
  name: orderservice-spc-sa
  namespace: default
  annotations:
    cce.io/dew-resource: "[\"orderservice-db-secret\"]"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orderservice-spc
spec:
  provider: cce
  parameters:
    objects: |
      - objectName: "orderservice-db-secret"  
        objectType: "csms"     
        objectVersion: "latest"        
        jmesPath:
          - path: username      
            objectAlias: username        
          - path: password 
            objectAlias: password
  secretObjects:
    - secretName: k8s-orderservice-db-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: orderservice-spc-sa
      containers:
      - name: order-service
        image: swr.cn-north-4.myhuaweicloud.com/itau-demo/order-service:0.0.1
        ports:
        - containerPort: 9080
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
        env:
          - name: DB_HOST_AND_PORT
            value: 172.16.0.173:3306
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8s-orderservice-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: k8s-orderservice-db-secret
                key: password
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: orderservice-spc

      imagePullSecrets:
      - name: default-secret

