apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: swr.cn-north-4.myhuaweicloud.com/itau-demo/order-service:0.0.1
        ports:
        - containerPort: 9080
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        env:
          - name: DB_HOST_AND_PORT
            value: 172.16.0.173:3306
      imagePullSecrets:
      - name: default-secret

